b2b_code_cms_form:
    resource:     "@B2bCodeCmsFormBundle/Controller/FormController.php"
    type:         annotation
    prefix:       /cms-form

b2b_code_cms_form_ajax_form:
    resource: "@B2bCodeCmsFormBundle/Controller/AjaxFormController.php"
    type: annotation
    prefix: /cms-form/ajax
    options:
        expose: true

b2b_code_cms_form_frontend_ajax_form:
    resource: "@B2bCodeCmsFormBundle/Controller/Frontend/AjaxFormController.php"
    type: annotation
    prefix: /cms-form/ajax
    options:
        frontend: true
        expose: true

b2b_code_cms_form_frontend_form:
    resource: "@B2bCodeCmsFormBundle/Controller/Frontend/FormController.php"
    type: annotation
    prefix: /cms-form
    options:
        frontend: true
        expose: true

#
# OLD REST API ROUTES
#

b2b_code_cms_form_api_formfield_delete:
    path: '/api/rest/{version}/formfield/{id}.{_format}'
    methods: [DELETE]
    defaults:
        _controller: 'B2bCode\Bundle\CmsFormBundle\Controller\Api\Rest\FormFieldController::deleteAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json|html
        version: latest|v1
